environments:
  QA:

    base_url: "https://thepetproject.com/"
    browser:
      - chrome
      - edge
      - firefox
      - safari
    email: "manish.sharma@gmail.com"
    password: "qwerty@05"

