environments:
  QA:

    base_url: "https://thepetproject.com/"
    browser:
      - chrome
      - edge
      - firefox
    email: "vishnu@gmail.com"
    password: "Vishnu@123"

dogs:
   DOGS_URL: "/collections/dog"
   DOG_GROOMING_URL: "/collections/dog-grooming"

