name: Pet Project Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest  # Pre-installed browsers!
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r requirements.txt
    - name: Run Tests
      env:
          BROWSER: ${{ matrix.browser }}
      run: pytest tests/ -v -s